### ISSUE TITLE
NBA Top Shot display issue

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#38] opened 2024-07-23 17:21 UTC
### Current Behavior

NBA Top Shot is currently lacking the correct icon and name when displayed throughout the product.

### Expected Behavior

- When displaying NBA Top Shot, we must ensure we have the correct icon and name displayed (eg: "NBA Top Shot" without hyphens)

## Steps to Reproduce

- Open Flow Wallet
- View an NBA Top Shot collection / NFT
- Observe no icon is displayed
- Observe the incorrect name "NBA-Top-Shot" (with hyphens) is used

## Expected Outcomes

- [ ] The correct NBA Top Shot icon is displayed
- [ ] The correct NBA Top Shot name (without hyphens) is displayed.

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

## Details:
<img width="383" alt="Screen Shot 2024-07-23 at 10 09 37 AM" src="https://github.com/user-attachments/assets/8ae7cf92-b71c-4492-90c9-c8ab8f2edecf">

**Comment by lmcmz** [comment] 2024-09-11 02:03
Close this, the root cause comes from NBATS is not configuring the right image on their contract

**Closed as completed by lmcmz** 2024-09-11 02:03 UTC
Labels: bug
