### ISSUE TITLE
[BUG] Total app/device crash upon transaction authorization

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#30] opened 2024-06-22 22:05 UTC
### Current Behavior

On Flow Wallet iOS, when the transaction authorization occurs, it sometimes appears twice, and upon selecting confirm or cancel on the second popup the entire app and phone will crash.

### Expected Behavior

- Transaction authorization popups appear just once and function as intended

### Steps To Reproduce

1. Navigate to increment.fi, and login with Flow Wallet iOS 
2. Select to preform a transaction (eg: Stake)
3. Observe 2 transaction authorization popups appear on the mobile app
4. Observe the mobile app crash and phone require a hard reset.

### Environment

```markdown
- iOS
```

**Comment by lmcmz** [comment] 2024-06-25 02:09
Fixed in new version 2.1.6, root cause is deadlock issue.

**Closed as completed by lmcmz** 2024-06-25 02:09 UTC
Labels: bug
